version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.yourdomain.com"
      ADMIN_TOKEN: "your-strong-admin-token"
      SIGNUPS_ALLOWED: "false"
      WEBSOCKET_ENABLED: "true"
    ports:
      - "8080:80"
      - "3012:3012"
    volumes:
      - ./vw-data:/data