name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    paths:
      - 'cloudflare-worker/**'
      - '.github/workflows/deploy-cloudflare-worker.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Publish to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd cloudflare-worker
          wrangler publish